### ISSUE TITLE
Resolución final

### ISSUE THREAD

**Issue by KevMCh** [KevMCh/rent_prices_analysis#2]
Primeros pasos de las conclusiones del proyecto.

**Comment by jvruoc** [comment]
El modelo que permite ver si un inmueble se va a alquilar en menos de 3 días da un f1 score de 0.20, es muy bajo, imagino porque el número de datos es muy pequeño.

Estoy probando modelos de regresión para el cálculo del precio del alquieler en función de características. Utilizo RandomForestRegressor()

**Comment by jvruoc** [comment]
Ya está finalizada la práctica, salvo cuestiones que salgan en la revisión. Antes de entregarla hay que unir cuadernos:
- final report.ipynb
- cleaning.ipynb
- analysis.ipynb
- model_regression.ipynb
