### ISSUE TITLE
Análisis de los datos

### ISSUE THREAD

**Issue by KevMCh** [KevMCh/rent_prices_analysis#4]
Aplicación de diferentes análisis de los datos.

**Comment by jvruoc** [comment]
He incluído el objetivo del modelo que es una clasificación entre "de venta rápida(<=3días) o no. Para ello se ha transformado un poco el dataset y he adaptado el análisis a esa trasformación.

En la rama de descripción del problema podrás ver la explicación del modelo.

Entre las adaptaciones he realizado la modificación del último hipótesis de contraste, ya que creo, que se trata de un contraste entre dos grupos "Dependientes" es decir, los mismos individuos antes y después de bajar el precio. Revísalo, por si ves algo mal.
